config/routes.rb
Rails.application.routes.draw do
  resources :gossip
  resources :users
  resources :city, only: [:show]
  resources :sessions

  root 'gossip#index'
  get '/contact', to: 'contact#contact'
  get '/equipe', to: 'team#team'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
    has_many :likes, dependent: :destroy
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :join_table_tag_to_gossips, dependent: :destroy
    has_many :tags, through: :join_table_tag_to_gossips
    has_many :comments, dependent: :destroy
    validates :title, length: { in: 3..30 }, presence: true
    validates :content, presence: true
end

app/models/join_table_pm_to_recipient.rb
class JoinTablePmToRecipient < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :private_message
end

app/models/join_table_tag_to_gossip.rb
class JoinTableTagToGossip < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :join_table_pm_to_recipients
    has_many :recipients, through: :join_table_pm_to_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :join_table_tag_to_gossips, dependent: :destroy
    has_many :gossips, through: :join_table_tag_to_gossips
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
    has_many :gossips, dependent: :destroy
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "JoinTablePmRecipient"
    has_many :comments, dependent: :destroy
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def index
  end

  def show
    @city = City.find(params[:id])
    @gossips = Gossip.where(user: User.where(city_id: params[:id]))
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    
    def contact
    end

end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
    before_action :authenticate_user, only: [:new, :create]
    before_action :super_user , only: [:edit,:update,:destroy]

    def index
        @gossips = Gossip.all
    end


    def show
        @gossip = Gossip.find(params[:id])
    end

    def new
        @gossip = Gossip.new
    end

    def create
        @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: session[:user_id])
  
        if @gossip.save
            flash[:success]
            redirect_to :root
        else 
            flash[:alert]
            render :new
        end 
    end

    def edit
        @gossip = Gossip.find(params[:id])
    end

    def update
        @gossip = Gossip.find(params[:id])
        if @gossip.update(post_params)
            redirect_to gossip_path(params[:id])
        else
            render :edit
        end
    end

    def destroy
        50.times do puts "#" end
        @gossip = Gossip.find(params[:id])
        @gossip.destroy
        redirect_to :root
    end

    private
    
    def post_params
        post_params = params.require(:gossip).permit(:title, :content)
    end

    def authenticate_user
        unless session[:user_id]
            flash[:danger] = "Please log in."
            redirect_to new_session_path
        end
    end

    def super_user
        unless session[:user_id] == Gossip.find(params[:id]).user
          flash[:danger] = "Vous n'êtes pas le créateur de ce potin....Si oui, prouvez le"
          redirect_to :root
        end
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        
    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            puts "yes"
            redirect_to :root
        else
            puts "aled"
            render :new
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to :root
    end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController

    def team
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    end
    
    def show
        @user = User.find(params[:id])
        @gossips = @user.gossips.all
    end  

    def new
        @user = User.new
        @cities = cities_list
    end

    def create
        @user = User.new(post_params)
        if @user.save
            redirect_to :root
        else
            render :new
        end
    end

    def edit

    end

    def update

    end

    def destroy

    end

    private

    def post_params
        post_params = params.require(:user).permit(:first_name,:last_name,:age,:city_id,:email,:password,:password_confirmation)
    end

    def cities_list
        cities =[]
        City.all.each {|city| cities << city}
        return cities
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include SessionsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
    end

    def logged_in?
        session.key?(:user_id)
    end
      
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/city/show.html.erb
<%= @city.name %><br><%= @city.zip_code %>

<div class="d-flex flex-wrap justify-content-center">
    <% @gossips.reverse_each do |gossip| %>
        <div class=" p-3  bg-body rounded border-bottom" style="width: 90%;">
            <div class="card-body row align-items-center">
                <div class="col-3">
                    <h5 class= "card-title"><%= gossip.title %></h5>
                </div>
                <div class="col">
                    <p class="card-text"><%= gossip.content %></p>
                </div>
                <div class="col-2">
                    <%= link_to "#{gossip.user.first_name}", user_path(gossip.user.id), :class => "card-text" %>
                </div>
                <div class="col-2 d-flex justify-content-end">
                    <%= link_to "Voir plus", gossip_path(gossip.id), :class => "btn btn-outline-dark" %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/contact/contact.html.erb
<div class="d-flex justify-content-center align-items-center min-vh-100">
    <h1>plus tard aussi</h1>
</div>

app/views/gossip/edit.html.erb
<div class="d-flex justify-content-center align-items-center min-vh-100">
    <div class= "text-center" style= "width : 500px">
        <h2>Modifier le potin</h2>
        <%= form_for @gossip do |f| %>
            <div class="m-3 ">
                <label>Titre</label>
                <%= f.text_field :title, class:'form-control'%>
            </div>
            <div class="m-3 ">
                <label>Contenu</label>
                <%= f.text_area :content, class:'form-control', style: "height: 200px"%>
            </div>
            <div class="">
                <button type="submit" class="btn btn-lg btn-primary mt-3">Modifier</button>
            </div>

        <% end %>
    </div>
</div>

app/views/gossip/index.html.erb
<% if flash[:success] %>
    <div class="container p-1 text-center alert alert-success" role="alert">

        <p>Nous avons réussi à créer le potin !</p>

    </div>
<% end %>

<% @gossips.reverse_each do |gossip| %>

    <div class="list-group ">
        <%= link_to gossip_path(gossip.id), :class => "list-group-item list-group-item-action py-3 bg-light" do %>
        <div class="d-flex mb-2 align-items-center gap-2">
        <img src="https://content-us.teletubbies.com/uploads/2016/03/tinky-winky.png" alt="twbs" width="32" height="32" class="rounded-circle">
        <object>
            <h6><%= link_to "#{gossip.user.first_name.capitalize}", user_path(gossip.user.id), :class => "fw-bold text-dark text-decoration-none" %></h6>
        </object>
        </div>
        <div class="d-flex gap-2 w-100 justify-content-between">
            <div>
                <h6 class="mb-0"><%= gossip.title %></h6>
                <p class="mb-0 opacity-75"><%= gossip.content %></p>
            </div>
            <div class= "d-flex flex-column align-items-end">
                <small class="opacity-50 text-nowrap"><%= gossip.created_at %></small>
                <small class="opacity-50 text-nowrap">Posté depuis : <%= gossip.user.city.name %></small>
            </div>
        </div>
        <% end %>
    </div>
<% end %>

app/views/gossip/new.html.erb
<% if flash[:alert] %>
    <div class="container p-1 text-center alert  alert-danger" role="alert">

        <p>Nous n'avons pas réussi à créer le potin !</p>

    </div>
<% end %>
<div class="d-flex justify-content-center align-items-center min-vh-100">
    <div class= "text-center" style= "width : 500px">
        <h2>Nouveau potin</h2>
        <%= form_with url: "/gossip", method: :post do |f| %>
            <div class="m-3 ">
                <label>Titre</label>
                <%= f.text_field :title, class:'form-control'%>
            </div>
            <div class="m-3 ">
                <label>Contenu</label>
                <%= f.text_area :content, class:'form-control', style: "height: 200px"%>
            </div>
            <div class="">
                <button type="submit" class="btn btn-lg btn-primary mt-3">Poster</button>
            </div>
        <% end %>
    </div>
</div>

app/views/gossip/show.html.erb
<div class="d-flex justify-content-center align-items-center min-vh-100">
    <div>
    <div class="card m-2" style="width: 18rem;">
        <div class="card-header">
            <h5 class= "card-title"><%= @gossip.title %></h5>
        </div>
        <div class="card-body">
            <p class="card-text"><%= @gossip.content %></p>
            <p class="card-text"><%= @gossip.user.first_name %></p>
            <p class="card-text"><%= @gossip.user.city.name %></p>
        </div>
        <%if session[:user_id]== @gossip.user.id%>
        <%= button_to 'supp', gossip_path(@gossip), method: :delete %>
        <%= link_to 'edit', edit_gossip_path(@gossip)%>
        <% end %>
    </div>

        <% @gossip.comments.reverse_each do |comment| %>
                <p><%= comment.content %></p>
                <p><%= comment.user.first_name %></p>
        <% end %>
    </div>
</div>

app/views/team/team.html.erb
<div class="d-flex justify-content-center align-items-center min-vh-100">
    <h1>plus tard</h1>
</div>

app/views/users/new.html.erb
<div class= "text-center">
    <%= form_for @user do |f| %>
        <h2>Création de compte</h2>
        <div class="m-3 ">
            <label>Prénom</label>
            <%= f.text_field :first_name, class:'form-control'%>
        </div>
        <div class="m-3">
            <label>Nom</label>
            <%= f.text_field :last_name, class:'form-control'%>
        </div>
        <div class="m-3">
            <label>Age</label>
            <%= f.number_field :age, in:18..99, class:'form-control'%>
        </div>
        <div class="m-3">
        <label>Ville</label><br>
        <%= f.collection_select :city_id, @cities, :id, :name,{}, class:'form-control' %>
        </div>
        <div class="m-3">
            <label>Email</label>
            <%= f.text_field :email, class:'form-control'%>
        </div>
        <div class="m-3">
            <label>Mot de passe</label>
            <%= f.password_field :password, class:'form-control'%>
            <label>Confirmer</label>
            <%= f.password_field :password_confirmation, class:'form-control'%>
        </div>
        <div class="">
            <button type="submit" class="btn btn-lg btn-primary mt-3">Inscription</button>
        </div>
    <% end %>
</div> 

app/views/users/show.html.erb
<div class="bg-image position-relative" style="background-image: url('https://i.pinimg.com/originals/35/f5/da/35f5dac58f756949d071f713311ed9ed.jpg'); background-position: center; background-repeat: no-repeat; background-size: cover; height: 300px; width: 100%;">
    <img src="https://content-us.teletubbies.com/uploads/2016/03/tinky-winky.png" alt="twbs" width="160" height="160" class="rounded-circle position-absolute top-100 translate-middle border border-light border-3" style= "left: 10%">
</div>
<div style = "height: 100px"></div>
<div class= "container-fluid">
    <div class= "row">
        <div class= "col-2">
            <ul class="list-group list-group-flush bg-light">
                <li class="list-group-item bg-light">
                    <small>Nom :</small><br>
                    <h6><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %></h6>
                </li>
                <li class="list-group-item bg-light">
                    <small>Age :</small><br>
                    <%= @user.age %> ans
                </li>
                <li class="list-group-item bg-light">
                    <small>Ville :</small><br>
                    <%= @user.city.name %>
                </li>
                <li class="list-group-item bg-light">
                    <small>Création le :</small><br>
                    <%= @user.created_at %>
                </li>
                <li class="list-group-item bg-light">
                    <small>Nombres de potins :</small><br>
                    <%= @gossips.length %>
                </li>
            </ul>
        </div>
        <div class= "col-10">
            <% @gossips.reverse_each do |gossip| %>

                <div class="list-group ">
                    <%= link_to gossip_path(gossip.id), :class => "list-group-item list-group-item-action py-3 bg-light" do %>
                    <div class="d-flex mb-2 align-items-center gap-2">
                    <img src="https://content-us.teletubbies.com/uploads/2016/03/tinky-winky.png" alt="twbs" width="32" height="32" class="rounded-circle">
                    <object>
                        <h6><%= link_to "#{gossip.user.first_name.capitalize}", user_path(gossip.user.id), :class => "fw-bold text-dark text-decoration-none" %></h6>
                    </object>
                    </div>
                    <div class="d-flex gap-2 w-100 justify-content-between">
                        <div>
                            <h6 class="mb-0"><%= gossip.title %></h6>
                            <p class="mb-0 opacity-75"><%= gossip.content %></p>
                        </div>
                        <div class= "d-flex flex-column align-items-end">
                            <small class="opacity-50 text-nowrap"><%= gossip.created_at %></small>
                            <small class="opacity-50 text-nowrap">Posté depuis : <%= gossip.user.city.name %></small>
                        </div>
                    </div>
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>

</div>