config/routes.rb
Rails.application.routes.draw do
  resources :gossip
  resources :users
  resources :city, only: [:show]
  resources :sessions

  root 'gossip#index'
  get '/contact', to: 'contact#contact'
  get '/equipe', to: 'team#team'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
    has_many :likes, dependent: :destroy
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :join_table_tag_to_gossips, dependent: :destroy
    has_many :tags, through: :join_table_tag_to_gossips
    has_many :comments, dependent: :destroy
    validates :title, length: { in: 3..30 }, presence: true
    validates :content, presence: true
end

app/models/join_table_pm_to_recipient.rb
class JoinTablePmToRecipient < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :private_message
end

app/models/join_table_tag_to_gossip.rb
class JoinTableTagToGossip < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :join_table_pm_to_recipients
    has_many :recipients, through: :join_table_pm_to_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :join_table_tag_to_gossips, dependent: :destroy
    has_many :gossips, through: :join_table_tag_to_gossips
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
    has_many :gossips, dependent: :destroy
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "JoinTablePmRecipient"
    has_many :comments, dependent: :destroy
    has_secure_password
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def index
  end

  def show
    @city = City.find(params[:id])
    @gossips = Gossip.where(user: User.where(city_id: params[:id]))
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    
    def contact
    end

end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
    before_action :authenticate_user, only: [:new, :create]
    before_action :super_user , only: [:edit,:update,:destroy]

    def index
        @gossips = Gossip.all
    end


    def show
        @gossip = Gossip.find(params[:id])
    end

    def new
        @gossip = Gossip.new
    end

    def create
        @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: session[:user_id])
  
        if @gossip.save
            flash[:success]
            redirect_to :root
        else 
            flash[:alert]
            render :new
        end 
    end

    def edit
        @gossip = Gossip.find(params[:id])
    end

    def update
        @gossip = Gossip.find(params[:id])
        if @gossip.update(post_params)
            redirect_to gossip_path(params[:id])
        else
            render :edit
        end
    end

    def destroy
        50.times do puts "#" end
        @gossip = Gossip.find(params[:id])
        @gossip.destroy
        redirect_to :root
    end

    private
    
    def post_params
        post_params = params.require(:gossip).permit(:title, :content)
    end

    def authenticate_user
        unless session[:user_id]
            flash[:danger] = "Please log in."
            redirect_to new_session_path
        end
    end

    def super_user
        unless session[:user_id] == Gossip.find(params[:id]).user
          flash[:danger] = "Vous n'êtes pas le créateur de ce potin....Si oui, prouvez le"
          redirect_to :root
        end
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        
    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            puts "yes"
            redirect_to :root
        else
            puts "aled"
            render :new
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to :root
    end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController

    def team
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    end
    
    def show
        @user = User.find(params[:id])
        @gossips = @user.gossips.all
    end  

    def new
        @user = User.new
        @cities = cities_list
    end

    def create
        @user = User.new(post_params)
        if @user.save
            redirect_to :root
        else
            render :new
        end
    end

    def edit

    end

    def update

    end

    def destroy

    end

    private

    def post_params
        post_params = params.require(:user).permit(:first_name,:last_name,:age,:city_id,:email,:password,:password_confirmation)
    end

    def cities_list
        cities =[]
        City.all.each {|city| cities << city}
        return cities
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include SessionsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
    end

    def logged_in?
        session.key?(:user_id)
    end
      
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TGP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application"%>
    <%= javascript_include_tag "application", defer: true %>
    
  </head>

  <body>
    <main class="container-fluid">
      <div class= "row">
        <div class="text-bg-dark vh-100 sticky-top col-2">
          <a class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none" href="/"><span class="fs-4">The Gossip Project</span></a>
          <hr>
          <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
              <a href="/" class="btn btn-dark" aria-current="page">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16"><path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/></svg>
                Home
              </a>
            </li>
            <li class="nav-item">
              <a href="/equipe" class="btn btn-dark" aria-current="page">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-emoji-sunglasses-fill" viewBox="0 0 16 16"><path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zM2.31 5.243A1 1 0 0 1 3.28 4H6a1 1 0 0 1 1 1v.116A4.22 4.22 0 0 1 8 5c.35 0 .69.04 1 .116V5a1 1 0 0 1 1-1h2.72a1 1 0 0 1 .97 1.243l-.311 1.242A2 2 0 0 1 11.439 8H11a2 2 0 0 1-1.994-1.839A2.99 2.99 0 0 0 8 6c-.393 0-.74.064-1.006.161A2 2 0 0 1 5 8h-.438a2 2 0 0 1-1.94-1.515L2.31 5.243zM4.969 9.75A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .866-.5z"/></svg>
                L'équipe
              </a>
            </li>
            <li class="nav-item">
              <a href="/contact" class="btn btn-dark" aria-current="page">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-heart-fill" viewBox="0 0 16 16"><path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555l-4.2 2.568a2.785 2.785 0 0 0-.051-.105c-.666-1.3-2.363-1.917-3.699-1.25-1.336-.667-3.033-.05-3.699 1.25l-.05.105L.05 3.555ZM11.584 8.91a4.694 4.694 0 0 1-.073.139L16 11.8V4.697l-4.003 2.447c.027.562-.107 1.163-.413 1.767Zm-4.135 3.05c-1.048-.693-1.84-1.39-2.398-2.082L.19 12.856A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144L10.95 9.878c-.559.692-1.35 1.389-2.398 2.081L8 12.324l-.551-.365ZM4.416 8.91c-.306-.603-.44-1.204-.413-1.766L0 4.697v7.104l4.49-2.752a4.742 4.742 0 0 1-.074-.138Z"/><path d="M8 5.993c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132Z"/></svg>
                Contact
              </a>
            </li>
          </ul>
          <hr>
          <ul class="nav nav-pills flex-column mb-auto">
            <% if logged_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user), :class => "btn btn-dark d-flex align-items-center gap-2" do %>
                  <img src="https://content-us.teletubbies.com/uploads/2016/03/tinky-winky.png" alt="twbs" width="32" height="32" class="rounded-circle">
                  <h6><%=current_user.first_name.capitalize%></h6>
                <% end %>
              </li>
              <li class="nav-item mt-4">
                <%= link_to "Nouveau potin", new_gossip_path, :class => "btn btn-success" %>
              </li>
              <li class="nav-item mt-4">
                <%= button_to "Déconexion", session_path(session.id), method: :delete, class: 'btn btn-outline-danger' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Connexion", new_session_path, :class => "btn btn-light" %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="bg-light col-10">
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>